### PR TITLE
Development merge, app tested

### PR DESCRIPTION
**Pull request by Typist01**
I just tested the app, it is working fine.

### CODE REVIEW

**Review by Baaartosz — COMMENTED** [review]
This message when viewing invalid data only suggests that I can type Yes to continue? What about if I want to quit?

``Would you like to view employee records? (y)``

**Comment by Typist01** [comment]
> This message when viewing invalid data only suggests that I can type Yes to continue? What about if I want to quit?
> 
> `Would you like to view employee records? (y)`
In the main viewer there is an isYes() method which is used for binary type responses.
Anything other than "yes", "yeah, "ye", "y" , "aye" defaults to no.

**Comment by Typist01** [comment]
So if the user enters no or anything other than yes responses, the program should eventually exit.

**Comment by Typist01** [comment]
This sort of interface I found in node's npm init command 
image
But I am open to any suggestions.

**Comment by Typist01** [comment]
Actually with npm, I think their message indicates that the default option is yes. I think it would be better to have
"(y/n)" just to remove this kind of confusion.

**Review by vladlogyin — APPROVED** [review]

**Pull request merged**
